"""NEXI - Intelligent web search CLI tool."""

__version__ = "0.1.0"

from nexi.config import (
    Config,
    ensure_config,
    get_config_path,
    load_config,
    save_config,
    run_first_time_setup,
    get_prompt_for_effort,
    EFFORT_LEVELS,
)
from nexi.tools import TOOLS, execute_tool, web_search, web_get
from nexi.history import (
    HistoryEntry,
    get_history_path,
    add_history_entry,
    get_last_n_entries,
    get_entry_by_id,
    get_latest_entry,
    clear_history,
    create_entry,
    format_entry_preview,
    format_entry_full,
)
from nexi.search import SearchResult, run_search, run_search_sync
from nexi.output import (
    get_console,
    set_plain_mode,
    is_tty,
    print_message,
    print_markdown,
    print_search_start,
    print_progress,
    print_answer,
    print_result_summary,
    print_error,
    print_warning,
    print_success,
    create_progress_callback,
)

__all__ = [
    "__version__",
    "Config",
    "ensure_config",
    "get_config_path",
    "load_config",
    "save_config",
    "run_first_time_setup",
    "get_prompt_for_effort",
    "EFFORT_LEVELS",
    "TOOLS",
    "execute_tool",
    "web_search",
    "web_get",
    "HistoryEntry",
    "get_history_path",
    "add_history_entry",
    "get_last_n_entries",
    "get_entry_by_id",
    "get_latest_entry",
    "clear_history",
    "create_entry",
    "format_entry_preview",
    "format_entry_full",
    "SearchResult",
    "run_search",
    "run_search_sync",
    "get_console",
    "set_plain_mode",
    "is_tty",
    "print_message",
    "print_markdown",
    "print_search_start",
    "print_progress",
    "print_answer",
    "print_result_summary",
    "print_error",
    "print_warning",
    "print_success",
    "create_progress_callback",
]
